// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ewatpgqdyxkqaqfbhvdh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV3YXRwZ3FkeXhrcWFxZmJodmRoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3ODMzMjEsImV4cCI6MjA2NDM1OTMyMX0.BhhVz7NcDtGDfZiEByfVG9rxC1ZPc_I_gHe0h-x8ERM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);